[package]
name = "propulsion_controller"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "propulsion_controller"
path = "src/main.rs"

[[bin]]
name = "propulsion_controller_tcp"
path = "src/bin/tcp_server.rs"

[dependencies]
